// THIS IS AN AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// You can update it by running `yarn generate-icons-sprite`

export const ICON_NAMES = [
  'arrow-down-line',
  'arrow-left',
  'arrow-right',
  'arrow-up-circle',
  'chevron-down',
  'close',
  'eye',
  'file',
  'home',
  'image',
  'land',
  'marker',
  'menu',
  'sort-down',
  'sort-up',
  'target',
  'world',
] as const

export type IconName = typeof ICON_NAMES[number]
